version: "3"

services:

  app:
    build: .
    image: flaskapp:1.0
    container_name: flaskapp
    hostname: flaskapp
    ports:
      - "8080:8080"
    environment:
      DATABASE_URI: "redis://redis:6379/0"
    depends_on:
      - redis
    networks:
      - web

  redis:
    image: redis:6-alpine
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - web

volumes:
  redis-data:

networks:
  web:
