version: "2.4"

services:
  app:
    build: .
    image: authserver:1.0
    container_name: authserver
    hostname: authserver
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/postgres"
    depends_on:
      - postgres
    networks:
      - web

  postgres:
    image: postgres:alpine
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - web

volumes:
  psql_data:

networks:
  web:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
